version: "3.8"

services:
  db: # EXPOSED_PORT = 5432
    image: postgres
    restart: always
    # volumes:
    #   - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      DATABASE_HOST: localhost
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: sa
      # - PGDATA=/var/lib/postgresql/data/pgdata
      POSTGRES_DB: schooldb
    expose:
      - "5432"

  api:
    build:
      context: .
      dockerfile: school-api.dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/SchoolApi/
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql+psycopg2://sa:12345678@db:5432/schooldb"      
      SQLALCHEMY_DATABASE_URL_ASYNC: "postgresql+asyncpg://sa:12345678@db:5432/schooldb"      
    command: bash -c "alembic upgrade head && uvicorn schoolapi.main:app --reload --host 0.0.0.0 --port 8000"