version: "3.8"

services:
  db: # EXPOSED_PORT = 5432
    image: postgres
    restart: always
    # volumes:
    #   - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    expose:
      - "5432"

  api:
    build:
      context: .
      dockerfile: school-api.dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/SchoolApi/
    env_file:
      - .env    
    command: bash -c "alembic upgrade head && uvicorn schoolapi.main:app --reload --host 0.0.0.0 --port 8000"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env