version: "3.8"

services:
  db: # EXPOSED_PORT = 5432
    image: postgres
    restart: always
    volumes:
      - ${VOLUME_NAME-app-db-data}:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    expose:
      - "5432"

  api:
    build:
      context: .
      dockerfile: school-api.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    environment:
      - SERVER_HOST=https://127.0.0.1:8000/docs
      - SMTP_HOST=${SMTP_HOST}
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/SchoolApi/
    env_file:
      - .env    
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: ./start.sh

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env

volumes:
  app-db-data:
  test-db-data: