"""Creating a relationship between the writer of the book and the book

Revision ID: 7b31fff34d83
Revises: 859abfa0e494
Create Date: 2023-04-10 21:57:22.404419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b31fff34d83'
down_revision = '859abfa0e494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'writer_id')
    # ### end Alembic commands ###
