"""Adding the relationship between Books and Users

Revision ID: 859abfa0e494
Revises: 0013ba7bc910
Create Date: 2023-04-09 20:25:20.279945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859abfa0e494'
down_revision = '0013ba7bc910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_book_id'), 'user_book', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_book_id'), table_name='user_book')
    op.drop_table('user_book')
    # ### end Alembic commands ###
