"""empty message

Revision ID: 9d9670b49f43
Revises: 
Create Date: 2022-12-30 21:08:21.851693

"""
import os
import json

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9670b49f43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher', 'student', name='role'), nullable=False),
    sa.Column('gender', sa.Enum('masculine', 'feminine', name='gender'), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    with open(os.path.join(os.path.dirname(__file__), "../data/users.json")) as f:
        user_data = f.read()

    op.bulk_insert(users, json.loads(user_data))
    
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
